apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "account.fullname" . }}-config
    labels:
        {{- include "account.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
    {{ $key }}: {{ $value | quote }}
{{- end }}