apiVersion: v1
kind: Secret
metadata:
    name: {{ include "account.fullname" . }}-secret
    labels:
        {{- include "account.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | quote }}
{{- end }}