apiVersion: v1
kind: Service
metadata:
  name: {{ include "account.fullname" . }}
  labels:
    {{- include "account.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "account.labels" . | nindent 4 }}
