services:
    accounts:
        image: "janagarajs/jbank-account:v5"
        ports:
            - "8080:8080"
        container_name: accounts-ms
        deploy:
            resources:
                limits:
                    memory: 700m
        networks:
            - "jbank"
        depends_on:
            - "mysql-db"

    mysql-db:
        image: "janagarajs/jbank-mysql:v2"
        ports:
            - "3307:3306"
        container_name: mysql-db
        environment:
            MYSQL_DATABASE: "accounts"
            MYSQL_USER: "accounts"
            MYSQL_PASSWORD: "accounts"
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            -   "C:/Janagaraj/docker-volumes/mysql-db:/var/lib/mysql"
        networks:
            - "jbank"

networks:
    jbank:
        driver: "bridge"