server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

build:
  version: "3.0.0"

accounts:
  message: "Welcome to JBank Accounts Service"
  contactDetails:
    name: "Janagaraj - Developer"
    email: "janagarajs@gmail.com"
  onCallSupport:
    - (224)123-4567
    - (224)123-4568