apiVersion: v1
kind: Secret
metadata:
    name: {{ include "jbank-db.fullname" . }}-secret
    labels:
        {{- include "jbank-db.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
    {{ $key }}: {{ $value | quote }}
{{- end }}