apiVersion: v1
kind: Service
metadata:
  name: {{ include "jbank-db.fullname" . }}
  labels:
    {{- include "jbank-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: mysql
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "jbank-db.labels" . | nindent 4 }}
