apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbank-mysql
  labels:
    app: jbank-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jbank-mysql
  template:
    metadata:
      name: jbank-mysql
      labels:
        app: jbank-mysql
    spec:
      containers:
        - name: jbank-mysql
          image: janagarajs/jbank-mysql:v3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: db-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-cm
                  key: db-user
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-db-cm
                  key: db-user
      restartPolicy: Always
      