apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbank-account-deployment
  labels:
    app: jbank-account-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jbank-account-deployment
  template:
    metadata:
      name: jbank-account-deployment
      labels:
        app: jbank-account-deployment
    spec:
      containers:
        - name: jbank-account-deployment
          image: janagarajs/jbank-account:v7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: account-cm
                  key: db-url
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: account-cm
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: account-secret
                  key: db-password
      restartPolicy: Always
      