name: ci.yml
on:
    #push:
    #    branches:
    #        - main
    #pull_request:
    #    branches:
    #        - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              token: '${{ secrets.GITHUB_TOKEN }}'
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Maven build
            run: mvn clean install -DskipTests
          - name: Get timestamp
            run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          - name: Build Docker image
            run: docker build -t ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          - name: Trivy scan
            uses: aquasecurity/trivy-action@master
            with:
              image-ref: '${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}'
              format: 'table'
              exit-code: 0
              ignore-unfixed: true
              vuln-type: 'os,library'
              severity: 'HIGH,CRITICAL'
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Push Docker image
            run: docker push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
          - name: Update tag in helm chart
            uses: mikefarah/yq@master
            with:
              cmd: yq -i '.image.tag = "${{ env.IMAGE_TAG }}"' helm-charts/account/values.yaml
          - name: Commit and push changes
            run: |
              git config --global user.email "bot@github.com"
              git config --local user.name "github-actions[bot]"
              git add helm-charts/account/values.yaml
              git commit -m "Update image tag to ${{ env.IMAGE_TAG }}"
              git push
